version: 0.2

env:
  variables:
    RDS_DB_NAME : "ebdb"
    RDS_USERNAME: "admin"
    RDS_PASSWORD: "test123!"
    RDS_HOSTNAME: "awseb-e-7sevd4snji-stack-awsebrdsdatabase-5xhtsbabrtyq.c4leokrb7cia.ap-northeast-2.rds.amazonaws.com"
    RDS_PORT: "3306"

phases:
  install:
    runtime-versions:
      dotnet: 6.0
  pre_build:
    commands:
      - dotnet restore TestEB/TestEB.csproj
  build:
    commands:
      - dotnet build TestEB/TestEB.csproj
  post_build:
    commands:
      - dotnet publish -c Release -o ./app/ TestEB/TestEB.csproj
artifacts:
  files:
    - '**/*'
