version: 0.2
phases:
  install:
    runtime-versions:
      dotnet: 6.0
  pre_build:
    commands:
      - dotnet restore TestEB/TestEB.csproj
  build:
    commands:
      - dotnet build TestEB/TestEB.csproj
  post_build:
    commands:
      - dotnet publish -c Release -o ./app/ TestEB/TestEB.csproj
artifacts:
  files:
    - '**/*'
